### ISSUE TITLE
What do you use the rbenv plugin for?

### ISSUE THREAD

**Issue by bucaran** [bpinto/oh-my-fish#402]
@daenney 

I don't use the `rbenv` plugin, instead I have this in my `fish` profile.

```fish
if not set -q RBENV_ROOT
# $HOME by default, but we can export RBENV_ROOT to a custom location.
# set -x RBENV_ROOT $HOME/path/to/.rbenv
end

if status --is-interactive
  # brew install xxenv will add the script to $PATH. Make sure to
  # symlink path/to/xxenv to /usr/local/bin in a custom install.
  . (rbenv init - | psub)
end
```

I realize I could get away with even less, but the above is dead simple and works.

What's the rbenv plugin doing that the above does not handle?

**Comment by daenney** [comment]
What I use the rbenv plugin for: to load rbenv support into fish :wink:.

The rbenv plugin takes care of it for me without me needing to add anything more than `rbenv` to my list of plugins. It means I have less to think about. It also takes care of correctly detecting where rbenv is located and pushing those locations onto `$PATH` which your solution does not.

For example, if `rbenv` is actually located in `$HOME/.rbenv/bin` your call to `rbenv init` will fail unless you've previously added `$HOME/.rben/bin` to your `$PATH`.

**Comment by bucaran** [comment]
@daenney I was making a huge mistake. I've updated the code above to `set -x RBENV_ROOT` in order to support custom installs.

Please see the updated code above.

> It also takes care of correctly detecting where rbenv is located and pushing those locations onto $PATH which your solution does not.

Why? Do you really need this? How did you install `rbenv`.

1. If you used `brew install rbenv` then `.rbenv` goes to `$HOME` and it will automatically symlink `~/.rbenv/bin/rbenv` to `/usr/local/bin`.
2. If you `git clone ... /rbenv` and installed it somewhere else, then you obviously know where it is so you just need to `set -x RBENV_ROOT path/to/rbenv`.

**Comment by daenney** [comment]
> If you used brew install rbenv then .rbenv goes to $HOME and it will automatically symlink ~/.rbenv/bin/rbenv to /usr/local/bin.

No it doesn't, read the code:
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/rbenv.rb

**Comment by daenney** [comment]
Your version still doesn't support having the shims and rubies installed in a different place either:

> * Added support for storing rbenv versions and shims in directories other than `~/.rbenv` with the `$RBENV_ROOT` environment variable.

**Comment by bucaran** [comment]
You are right, it does not do symlink anything. I wonder why not.

Well, it is essentially the same as git cloning it yourself.

**Comment by bucaran** [comment]
@daenney You are completely right, it does not symlink anything. I wonder why not. Thanks for pointing this out to me :+1: 

Well, it is essentially the same as git cloning it yourself, which is what I do before symlinking it to `/usr/local/bin` anyway. 

> This means that bin/ and shims/ and versions/ can be in completely different places on the filesystem.

I see. Why do you need this?

**Comment by daenney** [comment]
Because sometimes you want stuff in different places, depending on disk layouts and what not. Plus I don't want my home directory full of Ruby binaries, it's one of those things that I don't need backed up.

**Comment by bucaran** [comment]
@daenney I keep all the rubies __inside__ `$HOME/.rbenv`. I could use a different directory for `.rbenv` easily exporting `$RBENV_ROOT`, but the rubies would still go inside `.rbenv`.

I understand you do not always like this behavior and keep your rubies in a different place.

So, you do keep `.rbenv` inside `$HOME`, but the rubies in a different location. Is this correct?

**Comment by daenney** [comment]
> @daenney I keep all the rubies inside $HOME/.rbenv. I could use a different directory for .rbenv easily exporting $RBENV_ROOT, but rubies and gems would still go inside .rbenv/versions/{$VERSION}/.

No. By setting $RBENV_ROOT I relocate only `shims/` and `versions/`, not the whole of `.rbenv/`.

> (1) So, if I understand correctly, you keep .rbenv inside $HOME, but your rubies in a different location.

No. I install it from homebrew which means it's in `/usr/local/Cellar/rbenv/<version>` neatly symlinked onto my `$PATH` and my `shims/` and `versions/` are at `/usr/local/var/rbenv`.

> (2) What about the shims directory? They usually go in $RBENV_ROOT/shims, but I assume you also keep these in a different directory.

No. As I've stated before `RBENV_ROOT` is to be used to relocate both `versions/` and `shims/`.

> Finally, what are the environment variables you export to specify all these custom locations?

The only thing I export is `RBENV_ROOT`.

**Comment by bucaran** [comment]
I use `$RBENV_ROOT` to keep everything in the same directory, which I would think is a very common case as I find keeping everything distributed across my system rather a PITA, but now I understand your setup.

One more question, what's with this location `/usr/local/var/rbenv`? I see it's how it's defined in the formula.

**Comment by daenney** [comment]
I have no idea. You'd have to ask the Homebrew developers at to why they decided to place it there.
